#!/bin/bash

repo_folder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function link_dotfile_to_actual() {
    local dotfile_repo_path=$1
    local dotfile_target_path=$2
    local backup_folder=$3

    
}

function remove_dotfile() {
    local name=$1
    if [[ -z "${name}" ]] ; then
        echo "missing arguments. dotfiles.sh remove [backup-name]"
        exit 1
    fi

    echo -n "" > ${TMPDIR}/remove_dotfile
    while read -r line
    do
        local regex=".+:${name}:(.+)"

        if [[ ${line} =~ ${regex} ]]; then
            local actual_file=${BASH_REMATCH[1]}
            #restoring link
            rm ${actual_file}
            mv ${repo_folder}/${name} ${actual_file}
        else
            echo "${line}" >> ${TMPDIR}/remove_dotfile
        fi
    done < ${repo_folder}/dotfiles.lst
    mv ${TMPDIR}/remove_dotfile ${repo_folder}/dotfiles.lst
}

function add_dotfile() {
    local name=$1
    local dotfile=$2
    local encrypted=${3:-plain}
    if [[ -z "${dotfile}" ]] || [[ -z "${name}" ]] ; then
        echo "missing arguments. dotfiles.sh add/add-enc [full/path/to/.dotfile] [backup-name]"
        exit 1
    fi

    if [[ -f "${dotfile}" ]]; then
        remove_dotfile ${name}
        echo "${encrypted}:${name}:${dotfile}" >> dotfiles.lst
        uniq=($(cat ${repo_folder}/dotfiles.lst | sort -u))
        printf "%s\n" "${uniq[@]}" > ${repo_folder}/dotfiles.lst

        mv ${dotfile} ${repo_folder}/${name}
        ln -s ${repo_folder}/${name} ${dotfile}
    else
        echo "dotfile '${dotfile}' does not exist!"
        exit 1
    fi
}

function add_bin() {
    local required_bin=$1
    command -v ${required_bin} >/dev/null 2>&1 || { echo >&2 "required '${required_bin}' is not installed.  Aborting."; exit 1; }
    echo "${required_bin}" >> ${repo_folder}/required_bins.lst
    uniq=($(cat ${repo_folder}/required_bins.lst | sort -u))
    printf "%s\n" "${uniq[@]}" > ${repo_folder}/required_bins.lst
}

function remove_bin() {
    local name=$1
    if [[ -z "${name}" ]] ; then
        echo "missing arguments. dotfiles.sh remove-bin [required-bin-filename]"
        exit 1
    fi

    while read -r line
    do
        [[ ${line} != ${name} ]] && echo "${line}"
    done < required_bins.lst > ${TMPDIR}/remove_bin
    mv ${TMPDIR}/remove_bin ${repo_folder}/required_bins.lst
}

function verify_bins() {
    while IFS= read -r required_bin
    do
        echo -n "Checking ${required_bin} available.. "
        command -v ${required_bin} >/dev/null 2>&1 || { echo >&2 "required '${required_bin}' is not installed.  Aborting."; exit 1; }
        echo "✓"
    done < ${repo_folder}/required_bins.lst
}

function encrypt_file() {
    local file_to_encrypt=$1
    local encrypted_file=$2
    openssl enc -in ${file_to_encrypt} \
        -aes-256-cbc \
        -pass stdin > ${repo_folder}/${encrypted_file}
}

function decrypt_file() {
    local file_to_encrypt=$1
    local encrypted_file=$2
    
    openssl enc -in ${repo_folder}/${encrypted_file} \
        -d -aes-256-cbc \
        -pass stdin > ${file_to_encrypt}
}

function restore_links() {
    local regex="(.+):(.+):(.+)"
    local backup_folder="${HOME}/dotfiles_backup"

    while IFS= read -r dotfile_line
    do
        if [[ ${dotfile_line} =~ ${regex} ]]; then
            local encrypted=${BASH_REMATCH[1]}
            local repo_namefile=${BASH_REMATCH[2]}
            local actual_file=${BASH_REMATCH[3]}
            echo -n "Restoring '${actual_file}'... "
            if [[ -f ${actual_file} ]]; then
                local dotfile_backup=${backup_folder}${actual_file}
                echo -n "backing up to '${dotfile_backup}'... "
                mkdir -p $(dirname ${dotfile_backup}) || true
                mv ${actual_file} ${dotfile_backup}
                echo -n "💼 "
            fi
            #restoring link
            ln -s ${repo_folder}/${repo_namefile} ${actual_file}
            echo "✓"
        elif [[ ! -z ${dotfile_line} ]]; then
            echo "input line '${dotfile_line}' has illegal format!"
            exit 1
        fi
    done < ${repo_folder}/dotfiles.lst
}

case $1 in
    restore)
        echo "Restoring:"
        verify_bins
        restore_links
        echo "Done."
        ;;
    commit)
        echo "Committing:"
        pushd ${repo_folder} > /dev/null
        git status
        echo -n "Can I commit locally?"
        read continue_response
        if [[ "${continue_response}" == "y" ]]; then
            git add .
            commit_date=$(date '+%Y-%m-%d %H:%M:%S')
            git commit -m "dotfiles backup ${commit_date}"

            echo -n "Can I push to remote?"
            read continue_response
            if [[ "${continue_response}" == "y" ]]; then
                git push origin master
            fi    
        fi
        popd > /dev/null
        ;;
    add)
        echo -n "Adding backup $2 from dotfile $3: "
        add_dotfile $2 $3
        echo "✓"
        ;;
    add-enc)
        echo "Not supported at the moment"
        exit 1
        ;;
    remove)
        echo -n "Removing dotfile $2: "
        remove_dotfile $2
        echo "✓"
        ;;
    add-bin)
        echo -n "Adding bin $2: "
        add_bin $2
        echo "✓"
        ;;
    remove-bin)
        echo -n "Removing bin $2: "
        remove_bin $2
        echo "✓"
        ;;
    list)
        echo "* Required bins:"
        cat ${repo_folder}/required_bins.lst
        echo ""
        echo "* Managed dotfiles:"
        cat ${repo_folder}/dotfiles.lst
        ;;
    noop)
        #no-op. mostly here so the dirty check could be called.
        ;;
    *)
        echo "Supported commands:"
        echo "restore - links the dotfiles in this repo to the correct locations."
        echo "commit - commits and pushes local changes to repo."
        echo "add [backup-name] [full/path/to/.dotfile] - adds a dotfile to this repo with the given name."
        echo "*(not supported)* add-enc [backup-name] [full/path/to/.dotfile] - adds a dotfile to this repo with the given name, and encrypts it."
        echo "remove [backup-name] - removes a dotfile from the list of backuped dotfiles."
        echo "add-bin [binary-name] - adds a required bin."
        echo "remove-bin [binary-name] - removes a required bin."
        echo "list - prints out a list of all backup dotfiles and required bins."
    ;;
esac

if [[ $(git --git-dir=${repo_folder}/.git --work-tree=${repo_folder} diff --stat) != '' ]]; then
  echo "** [DOTFILES] your dotfiles repo is marked as dirty. You may want to push the recent changes to your remote repo by calling 'dotfiles commit'."
fi